prefixes = [
    '$PROJECT/$ENVIRONMENT/$SERVICE_NAME',
]
secrets = [
    '$PROJECT/$ENVIRONMENT/$SERVICE_NAME/DB_USER',
    '$PROJECT/$ENVIRONMENT/$SERVICE_NAME/DB_PASSWORD',
    '$PROJECT/$ENVIRONMENT/$SERVICE_NAME/API_SECRET',
    '$PROJECT/$ENVIRONMENT/$SERVICE_NAME/API_CERTIFICATE',
]

[[rename]]
    from = 'DB_USER'
    to = 'USERNAME'
[[rename]]
    from = 'DB_PASSWORD'
    to = 'PASSWORD'
[[rename]]
    from = 'SERVICE_DATABASE'
    to = 'DATABASE'
