prefix = "$PROJECT/$ENVIRONMENT/$SERVICE_NAME"
secrets = [
    "$PROJECT/$ENVIRONMENT/$SERVICE_NAME/DB_USER",
    "$PROJECT/$ENVIRONMENT/$SERVICE_NAME/DB_PASSWORD",
    "$PROJECT/$ENVIRONMENT/$SERVICE_NAME/API_SECRET",
    "$PROJECT/$ENVIRONMENT/$SERVICE_NAME/API_CERTIFICATE",
]
